name: Go
on: [ push, pull_request ]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - stable
        # Go 1.21 is the minimum version supported
        # - oldstable
    steps:

    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Test (default driver)
      run: go test -race -v ./...
    - name: Test (default driver without CGO)
      # -race requires CGO, so we disable -race
      run: CGO_ENABLED=0 go test -v ./...
    - name: Test github.com/mattn/go-sqlite3
      run: go test -race -v -ldflags="-X github.com/mattn/go-sqlite3.driverName=sqlite.mattn -X github.com/dolmen-go/sqlar/sqlarfs_test.sqliteDriver=sqlite.mattn" ./...
    - name: Test modernc.org/sqlite
      run: go test -race -v -tags=modernc ./...
    - name: Test github.com/ncruces/go-sqlite3
      run: go test -race -v -ldflags="-X github.com/ncruces/go-sqlite3/driver.driverName=sqlite.ncruces -X github.com/dolmen-go/sqlar/sqlarfs_test.sqliteDriver=sqlite.ncruces" -tags=sqlite.ncruces ./...
